// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: proto/token_checker.proto

package token_checker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TokenChecker_CheckTokenSafety_FullMethodName = "/tokenchecker.TokenChecker/CheckTokenSafety"
)

// TokenCheckerClient is the client API for TokenChecker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenCheckerClient interface {
	CheckTokenSafety(ctx context.Context, in *TokenSafetyRequest, opts ...grpc.CallOption) (*TokenSafetyResponse, error)
}

type tokenCheckerClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenCheckerClient(cc grpc.ClientConnInterface) TokenCheckerClient {
	return &tokenCheckerClient{cc}
}

func (c *tokenCheckerClient) CheckTokenSafety(ctx context.Context, in *TokenSafetyRequest, opts ...grpc.CallOption) (*TokenSafetyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenSafetyResponse)
	err := c.cc.Invoke(ctx, TokenChecker_CheckTokenSafety_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenCheckerServer is the server API for TokenChecker service.
// All implementations must embed UnimplementedTokenCheckerServer
// for forward compatibility.
type TokenCheckerServer interface {
	CheckTokenSafety(context.Context, *TokenSafetyRequest) (*TokenSafetyResponse, error)
	mustEmbedUnimplementedTokenCheckerServer()
}

// UnimplementedTokenCheckerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenCheckerServer struct{}

func (UnimplementedTokenCheckerServer) CheckTokenSafety(context.Context, *TokenSafetyRequest) (*TokenSafetyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckTokenSafety not implemented")
}
func (UnimplementedTokenCheckerServer) mustEmbedUnimplementedTokenCheckerServer() {}
func (UnimplementedTokenCheckerServer) testEmbeddedByValue()                      {}

// UnsafeTokenCheckerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenCheckerServer will
// result in compilation errors.
type UnsafeTokenCheckerServer interface {
	mustEmbedUnimplementedTokenCheckerServer()
}

func RegisterTokenCheckerServer(s grpc.ServiceRegistrar, srv TokenCheckerServer) {
	// If the following call pancis, it indicates UnimplementedTokenCheckerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TokenChecker_ServiceDesc, srv)
}

func _TokenChecker_CheckTokenSafety_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenSafetyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenCheckerServer).CheckTokenSafety(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenChecker_CheckTokenSafety_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenCheckerServer).CheckTokenSafety(ctx, req.(*TokenSafetyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenChecker_ServiceDesc is the grpc.ServiceDesc for TokenChecker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenChecker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tokenchecker.TokenChecker",
	HandlerType: (*TokenCheckerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckTokenSafety",
			Handler:    _TokenChecker_CheckTokenSafety_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/token_checker.proto",
}
